# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-01 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='hbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heros', to='book.BookInfo', verbose_name='图书'),
        ),
    ]
